FROM python:3.9-slim

WORKDIR /app

RUN pip install --upgrade pip

COPY requirements.txt .
RUN pip install -r requirements.txt

COPY . .

CMD ["celery", "-A", "celery_app.tasks", "flower", "--broker=redis://redis:6379/0", "--loglevel=DEBUG", "--port=5555"]
